# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "vcf_merge_variantcallers"
description: It takes vcf files from different variant callers and merge them into a single vcf file. 
keywords:
  - vcf
  - merge
components:
  - bcftools/merge
  - tabix/tabix
  - bcftools_query_stats
  - consensus_genotype
  - get_vcf_callers_info
  - create_sample_info

input:
  - ch_vcfs:
      type: file
      description: |
        The input channel containing the vcf and tbi files from different variant callers
        Structure: [ val(meta), [ path(vcfs) ], [ path(tbis) ] ]
      pattern: "*.{.vcf.gz}, *.{.vcf.gz.tbi}"
  - ch_fasta:
      type: file
      description: |
        Reference genome in FASTA format
        Structure: [ val(meta3), [ path(fasta) ] ]
      pattern: "*.{fasta,fa}"
  - ch_fai:
      type: file
      description: |
        Reference index in FAI format
        Structure: [ val(meta3), [ path(fai) ] ]
      pattern: "*.{fai}"
  - ch_intervals:
      type: file
      description: |
        Bed file with the genomic regions included in the library (optional)
        Structure: [ val(meta), [ path(bed) ] ]
  - assembly: 
      type: val
      description: |
        Assembly name to be used in the output file names
        e.g. "hg38"
      
output:
  - vcf:
      type: file
      description: |
        Channel containing merges vcf file
        Structure: [ val(meta), path(vcf), path(tbi) ]
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@yolandabq"
  - "@yocra3"
maintainers:
  - "@yolandabq"
  - "@yocra3"
