---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "splitmultiallelic"

description: Take a vcf file and split multiallelic variants into separate lines. In addition, it adds the program name to the header.
keywords:
  - annotation
  - vcf
  - format
tools:
  - "splitmultiallelic":
      description: "splitmultiallelic module takes a vcf file and split multiallelic variants into separate lines with bcftools.
        In addition, it adds the variant caller program name to the header with the format {samplename}.{program}."

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  
    - vcf:
        type: file
        description: vcf file 
        pattern: "*.{vcf.gz}"

    - tbi: 
        type: file
        description: vcf index
        pattern: "*.{vcf.gz.tbi}"

  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: "The fasta reference file"
        pattern: "*.{fasta,fa}"
  - - program: 
        type: val
        description: "Program name to add to the header"

output:

  - biallelic_renamed_vcf:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - vcf:
        type: file
        description: biallelic vcf file with program name in the header 
        pattern: "*.biallelic.${program}.vcf.gz"
    - tbi:
        type: file
        description: vcf index
        pattern: "*.biallelic.${program}.vcf.gz.tbi"


  
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@yolandabq"
maintainers:
  - "@yolandabq"
