# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "snv_annotation"
description: It takes vcf file to annoate SNVs and indels with VEP and adding additional annotations such as GLOWgenes, ROH regions, and MAF filtering.
keywords:
  - vcf
  - annotation
  - snv
  - indel
  - vep
  - glowgenes 
  - automap
  - postvep_modification
components:
  - format2info
  - automap
  - tabix/tabix
  - ensembl_vep/vep
  - postvep

input:
  - ch_vcfs:
      type: file
      description: |
        The input channel containing the vcf and tbi file.
        Structure: [ val(meta), [ path(vcfs) ], [ path(tbi) ] ]
      pattern_vcfs: "*.{.vcf.gz}"
      pattern_tbis: "*.{.vcf.gz.tbi}" 
  - ch_fasta:
      type: file
      description: |
        Reference genome in FASTA format
        Structure: [ val(meta2), [ path(fasta) ] ]
      pattern: "*.{fasta,fa}"
  - genome:
      type: string
      description: |
        Which genome to annotate with
        e.g. "GRCh37", "GRCh38"
      pattern: "*.{fai}"
  - species:
      type: string
      description: |
        which species to annotate with
        e.g. "homo_sapiens"
  - cache_version:
      type: integer
      description: |
        which version of the cache to annotate with
  - ch_cache_path: 
      type: path
      description: |
        Path to VEP cache
  - ch_custom_extra_files:
      type: file
      description: | 
        path to file(s) needed for plugins  (optional)
  - ch_extra_files:
      type: file
      description: |
        path to file(s) needed for other custom annotations  (optional)
  - maf: 
      type: integer
      description: |
        MAF value to use as threshold for filtering
  
  - ch_glowgenes_panel: 
      type: file
      description: GLOWgenes gene ranking file. It can be a local file or a precomputed file from the GLOWgenes github. Diseases available at in https://github.com/TBLabFJD/GLOWgenes/blob/master/precomputed_panelAPP/GLOWgenes_precomputed_panelAPP.tsv
  
  - ch_glowgenes_sgds: 
      type: file
      description: Score of Gene-Disease Associations (SGDs) file. Available at https://github.com/TBLabFJD/GLOWgenes/blob/master/precomputed_panelAPP/GLOWgenes_precomputed_panelAPP.tsv

      
output:
  - tsv:
      type: file
      description: |
        Annotated tsv file with SNVs and indels
        Structure: [ val(meta), path(tsv) ]
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@yolandabq"
  - "@yocra3"
  - "@guriaregojo"
maintainers:
  - "@yolandabq"
  - "@yocra3"
  - "@guriaregojo"
