# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "check_process_automap"
description: Check if the vcf file contains more than 10000 variants and run automap if so.
keywords:
  - vcf
  - automap
components:
  - validate_automap
  - automap


input:
  - ch_vcf:
      type: file
      description: |
        The input channel containing the vcf file
        Structure: [ val(meta), path(vcf)]
      pattern: "*.{vcf.gz}"

  - assembly: 
      type: val
      description: |
        Assembly name to be used in the output file names
        e.g. "hg38"
      
output:
  - automap:
      type: file
      description: |
        Path to the HomRegion file in tsv format.
        Structure: [ val(meta), path(tsv)]

authors:
  - "@yolandabq"
  - "@yocra3"
maintainers:
  - "@yolandabq"
  - "@yocra3"
